// This file was automatically generated by ImGuiWidget code generator
// Generated at: Aug  4 2025 17:04:25

#include "ImWidget.h"
#include "ImButton.h" // Include specific widget headers
#include "imgui.h"

using namespace ImGuiWidget;

void Setupbutton0()
{
    // Create the widget
    ImButton* button0 = new ImButton("button0");

    // Initialization code for button0 (class ImWindows::ImMenuButton)
    button0.SetPropertyValue<ImU32>("BackGroundColor", IM_COL32(255, 255, 255, 255));
    button0.SetPropertyValue<bool>("HaveBorder", true);
    // Initialize PressedStyle properties
        button0.GetPressedStyle().SetPropertyValue<ImU32>("BackgroundColor", IM_COL32(250, 220, 190, 120));
        button0.GetPressedStyle().SetPropertyValue<bool>("HasBorder", false);
        button0.GetPressedStyle().SetPropertyValue<float>("Rounding", 0.000000f);
        button0.GetPressedStyle().SetPropertyValue<float>("BorderThickness", 1.000000f);
        button0.GetPressedStyle().SetPropertyValue<ImU32>("BorderColor", IM_COL32(255, 255, 255, 255));
    button0.SetPropertyValue<ImU32>("BorderColor", IM_COL32(0, 0, 0, 255));
    // Initialize NormalStyle properties
        button0.GetNormalStyle().SetPropertyValue<ImU32>("BackgroundColor", IM_COL32(0, 255, 0, 255));
        button0.GetNormalStyle().SetPropertyValue<bool>("HasBorder", false);
        button0.GetNormalStyle().SetPropertyValue<float>("Rounding", 0.000000f);
        button0.GetNormalStyle().SetPropertyValue<float>("BorderThickness", 1.000000f);
        button0.GetNormalStyle().SetPropertyValue<ImU32>("BorderColor", IM_COL32(255, 255, 255, 255));
    button0.SetPropertyValue<std::string>("TooltipText", "Project");
    // Initialize HoveredStyle properties
        button0.GetHoveredStyle().SetPropertyValue<ImU32>("BackgroundColor", IM_COL32(230, 200, 170, 120));
        button0.GetHoveredStyle().SetPropertyValue<bool>("HasBorder", false);
        button0.GetHoveredStyle().SetPropertyValue<float>("Rounding", 0.000000f);
        button0.GetHoveredStyle().SetPropertyValue<float>("BorderThickness", 1.000000f);
        button0.GetHoveredStyle().SetPropertyValue<ImU32>("BorderColor", IM_COL32(255, 255, 255, 255));

    // Additional setup can be added here
}
